const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});
 const base=process.env.TEST_URL||'http://localhost:8080';
 const c=await b.newContext({viewport:{width:375,height:812}}); const p=await c.newPage();
 let requests=[];p.on('request',r=>{if(/google-analytics|googletagmanager|doubleclick/.test(r.url()))requests.push(r.url())});
 await p.route('https://www.googletagmanager.com/**',r=>r.fulfill({body:'',contentType:'text/javascript'}));
 await p.goto(base);await p.waitForTimeout(300);
 assert.equal(requests.length,0);assert.equal((await c.cookies()).filter(x=>x.name.startsWith('_ga')).length,0);
 assert(await p.locator('#privacy-choices').isVisible());
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.locator('#privacy-decline').click();await p.reload();assert.equal(requests.length,0);assert(await p.locator('#privacy-choices').isHidden());
 await p.locator('#privacy-settings').click();await p.locator('#privacy-accept').click();assert.equal(requests.length,1);
 const data=await p.evaluate(()=>dataLayer.map(x=>Array.from(x)));
 assert.equal(data.find(x=>x[0]==='consent'&&x[1]==='default')[2].analytics_storage,'denied');
 const config=data.find(x=>x[0]==='config')[2];assert.equal(config.allow_google_signals,false);
 await c.addCookies([{name:'_ga',value:'old',url:base}]);
 await p.locator('#privacy-settings').click();await p.locator('#privacy-decline').click();await p.waitForTimeout(500);
 assert.equal(requests.length,1);assert.equal((await c.cookies()).filter(x=>x.name.startsWith('_ga')).length,0);
 await p.locator('#privacy-settings').click();await p.locator('#privacy-ads').click();
 const ads=await p.evaluate(()=>dataLayer.map(x=>Array.from(x)));
 assert(ads.some(x=>x[0]==='consent'&&x[1]==='update'&&x[2].ad_personalization==='granted'));
 assert.equal(ads.find(x=>x[0]==='config')[2].allow_google_signals,true);
 await p.reload();await p.waitForTimeout(200);assert(await p.locator('#privacy-choices').isHidden());
 await p.locator('#privacy-settings').click();await p.locator('#privacy-accept').click();await p.waitForTimeout(500);
 const reduced=await p.evaluate(()=>dataLayer.map(x=>Array.from(x)));
 assert.equal(reduced.find(x=>x[0]==='config')[2].allow_google_signals,false);
 const n=await b.newContext({javaScriptEnabled:false});const np=await n.newPage();await np.goto(base+'/privacy_policy.html');assert(await np.locator('#privacy-choices').isHidden());assert(await np.locator('#privacy-status').isVisible());
 await b.close();console.log('PASS consent defaults, no pre-consent requests/cookies, decline persistence, opt-in, withdrawal, cookie removal, mobile width and no-JS');
})().catch(e=>{console.error(e);process.exit(1)});
